### ISSUE TITLE
Вот и появился вопрос по Fork

### ISSUE THREAD

**Issue by KniginAleksey** [volodymyr-kushnir/agenda#21]
В конце статьи написано:  "Форкнути їх собі не вийде, адже жоден з авторів не позначив свій репозиторій ліцензією з дозволом на копіювання і зміну."

Это значит что нельзя, т.к. нет лицензии? Или не получиться, т.к. нет доступа?

P.S. А то я себе уже форкнул, уж очень полезной была статья. Но я удалю, если что))

**Comment by volodymyr-kushnir** [comment]
@KniginAleksey там малося на увазі, шо не вийде на їх основі шось зробити. Я просто бачив як хтось починав свій проект з форку проекту іншого учасника і просто не поняв для чого то робити:
1) ліцензії нема, відтак форкнути то можна, але змінювати нє
2) якось дуже палєвно би вийшло.

Хоча може це просто хлопці/дівчата клікнули випадково **Edit** на **GitHub**'і, а **GitHub** зразу в таких випадках форк робить і потім після редагування **Pull Request** відправляє.

А форк лишай якшо хочеш, але ж там цінної інформації на 5 хвилин. Тепер ти то всьо знаєш і воно тобі більше і нафіг не треба (:

**Comment by KniginAleksey** [comment]
Ясно. Спасибо. Пусть побудет у меня. Кушать пока не просит))
